--[[
    药水效果数据 (PotionEffectData.lua)
    由 potionEffect.json 转换而来
    每个效果包含：id, oppositeId, name, potionBaseId, poisonBaseId, index
    index 用于效果排序，potionBaseId/poisonBaseId 用于确定物品 ID
]]

DataExtractor.PotionEffects = {
    [1] = {
        id = 1,
        oppositeId = 2,
        name = "回复生命",
        potionBaseId = 54339,
        poisonBaseId = 76826,
        index = 18,
    },
    [2] = {
        id = 2,
        oppositeId = 1,
        name = "损害生命",
        potionBaseId = 44812,
        poisonBaseId = 76827,
        index = 5,
    },
    [3] = {
        id = 3,
        oppositeId = 4,
        name = "回复魔力",
        potionBaseId = 54340,
        poisonBaseId = 76828,
        index = 19,
    },
    [4] = {
        id = 4,
        oppositeId = 3,
        name = "损害魔力",
        potionBaseId = 44815,
        poisonBaseId = 76829,
        index = 6,
    },
    [5] = {
        id = 5,
        oppositeId = 6,
        name = "回复耐力",
        potionBaseId = 54341,
        poisonBaseId = 76830,
        index = 20,
    },
    [6] = {
        id = 6,
        oppositeId = 5,
        name = "损害耐力",
        potionBaseId = 44809,
        poisonBaseId = 76831,
        index = 7,
    },
    [7] = {
        id = 7,
        oppositeId = 8,
        name = "提高法术抗性",
        potionBaseId = 44814,
        poisonBaseId = 76832,
        index = 23,
    },
    [8] = {
        id = 8,
        oppositeId = 7,
        name = "破甲",
        potionBaseId = 44821,
        poisonBaseId = 76833,
        index = 25,
    },
    [9] = {
        id = 9,
        oppositeId = 10,
        name = "提高护甲",
        potionBaseId = 27042,
        poisonBaseId = 76837,
        index = 24,
    },
    [10] = {
        id = 10,
        oppositeId = 9,
        name = "断裂",
        potionBaseId = 27040,
        poisonBaseId = 76835,
        index = 26,
    },
    [11] = {
        id = 11,
        oppositeId = 12,
        name = "提高法术威力",
        potionBaseId = 30145,
        poisonBaseId = 76840,
        index = 12,
    },
    [12] = {
        id = 12,
        oppositeId = 11,
        name = "怯懦",
        potionBaseId = 44813,
        poisonBaseId = 76834,
        index = 14,
    },
    [13] = {
        id = 13,
        oppositeId = 14,
        name = "提高武器威力",
        potionBaseId = 44714,
        poisonBaseId = 76838,
        index = 13,
    },
    [14] = {
        id = 14,
        oppositeId = 13,
        name = "致残",
        potionBaseId = 44810,
        poisonBaseId = 76839,
        index = 15,
    },
    [15] = {
        id = 15,
        oppositeId = 16,
        name = "法术暴击率",
        potionBaseId = 30141,
        poisonBaseId = 76836,
        index = 16,
    },
    [16] = {
        id = 16,
        oppositeId = 15,
        name = "混乱",
        potionBaseId = 54336,
        poisonBaseId = 76841,
        index = 8,
    },
    [17] = {
        id = 17,
        oppositeId = 18,
        name = "提高武器暴击率",
        potionBaseId = 30146,
        poisonBaseId = 76842,
        index = 17,
    },
    [18] = {
        id = 18,
        oppositeId = 17,
        name = "虚弱",
        potionBaseId = 54337,
        poisonBaseId = 76843,
        index = 9,
    },
    [19] = {
        id = 19,
        oppositeId = 20,
        name = "势不可挡",
        potionBaseId = 27039,
        poisonBaseId = 76844,
        index = 2,
    },
    [20] = {
        id = 20,
        oppositeId = 19,
        name = "诱捕",
        potionBaseId = 54333,
        poisonBaseId = 76845,
        index = 4,
    },
    [21] = {
        id = 21,
        oppositeId = 22,
        name = "侦测",
        potionBaseId = 30142,
        poisonBaseId = 76847,
        index = 3,
    },
    [22] = {
        id = 22,
        oppositeId = 21,
        name = "隐形",
        potionBaseId = 44715,
        poisonBaseId = 76844,
        index = 10,
    },
    [23] = {
        id = 23,
        oppositeId = 24,
        name = "速度",
        potionBaseId = 27041,
        poisonBaseId = 0,
        index = 11,
    },
    [24] = {
        id = 24,
        oppositeId = 23,
        name = "阻碍",
        potionBaseId = 54335,
        poisonBaseId = 81196,
        index = 1,
    },
    [25] = {
        id = 25,
        oppositeId = 26,
        name = "保护",
        potionBaseId = 77596,
        poisonBaseId = 77597,
        index = 27,
    },
    [26] = {
        id = 26,
        oppositeId = 25,
        name = "脆弱",
        potionBaseId = 77598,
        poisonBaseId = 77599,
        index = 28,
    },
    [27] = {
        id = 27,
        oppositeId = 28,
        name = "绵长生命",
        potionBaseId = 77592,
        poisonBaseId = 77593,
        index = 21,
    },
    [28] = {
        id = 28,
        oppositeId = 27,
        name = "渐进生命损害",
        potionBaseId = 77594,
        poisonBaseId = 81195,
        index = 22,
    },
    [29] = {
        id = 29,
        oppositeId = 30,
        name = "活力",
        potionBaseId = 77600,
        poisonBaseId = 77601,
        index = 29,
    },
    [30] = {
        id = 30,
        oppositeId = 29,
        name = "亵渎",
        potionBaseId = 77602,
        poisonBaseId = 77603,
        index = 30,
    },
    [31] = {
        id = 31,
        oppositeId = 32,
        name = "英勇",
        potionBaseId = 151969,
        poisonBaseId = 152151,
        index = 31,
    },
    [32] = {
        id = 32,
        oppositeId = 31,
        name = "胆怯",
        potionBaseId = 151969,
        poisonBaseId = 152151,
        index = 32,
    },
}
